# Generated by Django 5.0.2 on 2024-03-09 10:14

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Extension', models.CharField(max_length=20)),
                ('Currency', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=10)),
                ('Frac', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('Sector', models.CharField(max_length=50)),
                ('Cap', models.CharField(choices=[('Large', 'Large'), ('Mid', 'Mid'), ('Small', 'Small')], max_length=10)),
                ('Company', models.CharField(max_length=100)),
                ('Symbol', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Display', models.CharField(max_length=16)),
                ('CLS_Price', models.FloatField(null=True)),
                ('EOD_Price', models.FloatField(null=True)),
                ('Expected_Price', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('net_return', models.FloatField(null=True)),
                ('risk', models.FloatField(null=True)),
                ('probability', models.FloatField(null=True)),
                ('market_contri_reg', models.FloatField(null=True)),
                ('momentum_contri_reg', models.FloatField(null=True)),
                ('mean_reversion_contri_reg', models.FloatField(null=True)),
                ('voltality_contri_reg', models.FloatField(null=True)),
                ('volume_contri_reg', models.FloatField(null=True)),
                ('market_contri_class', models.FloatField(null=True)),
                ('momentum_contri_class', models.FloatField(null=True)),
                ('mean_reversion_contri_class', models.FloatField(null=True)),
                ('voltality_contri_class', models.FloatField(null=True)),
                ('volume_contri_class', models.FloatField(null=True)),
                ('Exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Broker.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Units', models.IntegerField()),
                ('Invested', models.FloatField(null=True)),
                ('Current_Value', models.FloatField(null=True)),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Broker.stock')),
                ('Trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Profit_Loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realized_profit_loss', models.FloatField(default=0, null=True)),
                ('Exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Broker.exchange')),
                ('Trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trade_Type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4)),
                ('Trade_Qty', models.IntegerField()),
                ('Trade_Price', models.FloatField(null=True)),
                ('Trade_Date', models.DateTimeField(auto_now_add=True)),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Broker.stock')),
                ('Trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='stock_profit_loss',
            constraint=models.UniqueConstraint(fields=('Trader', 'Exchange'), name='unique_trader_exchange'),
        ),
    ]
