# Generated by Django 4.1 on 2024-02-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Broker", "0008_valuation"),
    ]

    operations = [
        migrations.RemoveField(model_name="option_portfolio", name="Option",),
        migrations.RemoveField(model_name="option_portfolio", name="Trader",),
        migrations.RemoveField(model_name="option_profit_loss", name="Trader",),
        migrations.RemoveField(model_name="option_trade", name="Option",),
        migrations.RemoveField(model_name="option_trade", name="Trader",),
        migrations.RemoveField(model_name="valuation", name="Stock",),
        migrations.RenameField(
            model_name="stock", old_name="high_price", new_name="market_contri_class",
        ),
        migrations.RenameField(
            model_name="stock", old_name="low_price", new_name="market_contri_reg",
        ),
        migrations.RemoveField(model_name="stock_trade", name="Trade_Method",),
        migrations.AddField(
            model_name="stock",
            name="mean_reversion_contri_class",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="mean_reversion_contri_reg",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="momentum_contri_class",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="momentum_contri_reg",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="stock", name="net_return", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="stock", name="probability", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="voltality_contri_class",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="voltality_contri_reg",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="volume_contri_class",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="volume_contri_reg",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="Symbol",
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(name="Option",),
        migrations.DeleteModel(name="Option_Portfolio",),
        migrations.DeleteModel(name="Option_Profit_Loss",),
        migrations.DeleteModel(name="Option_Trade",),
        migrations.DeleteModel(name="Valuation",),
    ]
