# Generated by Django 4.1 on 2024-02-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Broker",
            "0010_remove_stock_profit_loss_id_alter_stock_portfolio_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stock", name="risk", field=models.FloatField(null=True),
        ),
    ]
