# Generated by Django 4.1 on 2024-02-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Broker", "0011_stock_risk"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="Cap",
            field=models.CharField(
                choices=[("Large", "Large"), ("Mid", "Mid"), ("Small", "Small")],
                default="Large",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
