# Generated by Django 5.0.2 on 2024-02-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Broker', '0012_stock_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='EOD_Price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Expected_Price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='net_return',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stock_portfolio',
            name='Current_Value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock_portfolio',
            name='Invested',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock_profit_loss',
            name='realized_profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock_trade',
            name='Trade_Price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
