# Generated by Django 5.0.2 on 2024-02-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Broker', '0014_alter_stock_net_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='CLS_Price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
