# Generated by Django 5.0.2 on 2024-02-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Broker', '0015_stock_cls_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='CLS_Price',
        ),
    ]
