# Generated by Django 5.0.2 on 2024-02-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Broker', '0016_remove_stock_cls_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='CLS_Price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
