# Generated by Django 5.0.2 on 2024-02-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Broker', '0023_alter_stock_cls_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='CLS_Price',
            field=models.FloatField(),
        ),
    ]
