# Generated by Django 5.0.2 on 2024-02-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Broker', '0026_alter_stock_cls_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='CLS_Price',
            field=models.FloatField(null=True),
        ),
    ]
