# Generated by Django 4.1 on 2024-02-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Broker", "0030_alter_stock_cls_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock", name="CLS_Price", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="stock", name="EOD_Price", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="Expected_Price",
            field=models.FloatField(null=True),
        ),
    ]
