# Generated by Django 5.0.2 on 2024-02-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Broker', '0031_alter_stock_cls_price_alter_stock_eod_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_portfolio',
            name='Current_Value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_portfolio',
            name='Invested',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_profit_loss',
            name='realized_profit_loss',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock_trade',
            name='Trade_Price',
            field=models.FloatField(null=True),
        ),
    ]
