name: Update NYSE Data Finance

on:
  schedule:
    - cron: '*/5 * * * *'  # This is the cron expression to run every 5 minutes

jobs:
  my_job:
    runs-on: ubuntu-latest  # You can change this based on your environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m venv venv                
          source venv/bin/activate           
          pip install --upgrade pip          
          pip install django                 
          pip install yfinance
          pip install psycopg2

      - name: Run script or command
        run: |
          source venv/bin/activate
          python update_data_nyse_finance.py
